name: h3_ffi_plus
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 1.0.0+v4.2.1
homepage: https://github.com/festelo/h3_dart
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  path: ^1.8.1
  h3_common_plus: 
    path: "../h3_common_plus"

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.0
  ffigen: ^6.0.1
  collection: ^1.17.1
