name: h3_dart
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 0.6.2
homepage: https://github.com/festelo/h3_dart
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  h3_ffi: 
    path: "../h3_ffi"
  h3_web:
    path: "../h3_web"
  h3_common:
    path: "../h3_common"
  geojson2h3:
    path: "../geojson2h3"

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.3
