name: h3_dart_plus
description: Cross-platform Dart H3 bindings built on the abstract interface from h3_common_plus, using h3_ffi_plus and h3_web_plus as platform-specific implementations.
version: 1.0.0+v4.2.1
homepage: https://github.com/codewithsam110g/h3_flutter_bindings

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  ffi: ^2.0.1
  h3_ffi_plus: ^1.0.0 
  h3_web_plus: ^1.0.0
  h3_common_plus: ^1.0.0
  geojson2h3_plus: ^1.0.0

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.3
