name: h3_dart_plus
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 1.0.0+v4.2.1
homepage: https://github.com/festelo/h3_dart
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  h3_ffi_plus: 
    path: "../h3_ffi_plus"
  h3_web_plus:
    path: "../h3_web_plus"
  h3_common_plus:
    path: "../h3_common_plus"
  geojson2h3_plus:
    path: "../geojson2h3_plus"

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.3
