name: h3_common_plus
description: This package provides the base abstract class for all other H3 packages in the _plus ecosystem.
version: 1.0.0+v4.2.1
homepage: https://github.com/codewithsam110g/h3_flutter_bindings

environment:
  sdk: ">=2.14.0 <4.0.0"

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.0