name: geojson2h3_plus
description: The geojson2h3 library includes a set of utilities for conversion between GeoJSON polygons and H3 hexagon indexes, using h3. Inspired by JS library geojson2h3.
version: 1.0.0+v4.2.1
homepage: https://github.com/festelo/h3_dart
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  h3_common_plus:
    path: "../h3_common_plus"

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.1.11
