name: h3_web
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 0.6.1
homepage: https://github.com/festelo/h3_dart
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  js: ^0.6.4
  h3_common:
    path: "../h3_common"

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.0
  collection: ^1.16.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  build_test: ^2.1.5
