name: h3_web_plus
description: Dart JS interop implementation of the abstract H3 interface from h3_common_plus. Not intended for direct use.
version: 1.0.0+v4.2.1
homepage: https://github.com/codewithsam110g/h3_flutter_bindings

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  js: ^0.6.4
  h3_common_plus: ^1.0.0

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.0
  collection: ^1.16.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  build_test: ^2.1.5
