name: h3_flutter_plus
description: H3 bindings for Flutter, built on the abstract interface from h3_common_plus, using h3_ffi_plus and h3_web_plus as platform-specific implementations.
version: 1.0.0+v4.2.1
homepage: https://github.com/codewithsam110g/h3_flutter_bindings

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  h3_ffi_plus: ^1.0.0
  h3_web_plus: ^1.0.0
  h3_common_plus: ^1.0.0
  geojson2h3_plus: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.h3_flutter
        pluginClass: H3FlutterPlugin
      ios:
        pluginClass: H3FlutterPlugin
      macos:
        pluginClass: H3FlutterPlugin
      web:
        default_package: h3_web_plus
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
