name: h3_flutter
description: The package provides Flutter version of the H3 Core library, a hexagon-based geographic grid system
version: 0.6.6
homepage: https://github.com/festelo/h3_dart
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  h3_ffi: 
    path: "../h3_ffi"
  h3_web:
    path: "../h3_web"
  h3_common:
    path: "../h3_common"
  geojson2h3:
    path: "../geojson2h3"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.h3_flutter
        pluginClass: H3FlutterPlugin
      ios:
        pluginClass: H3FlutterPlugin
      macos:
        pluginClass: H3FlutterPlugin
      web:
        default_package: h3_web
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
