name: h3_flutter_plus
description: The package provides Flutter version of the H3 Core library, a hexagon-based geographic grid system
version: 1.0.0+v4.2.1
homepage: https://github.com/festelo/h3_dart
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  h3_ffi_plus: 
    path: "../h3_ffi_plus"
  h3_web_plus:
    path: "../h3_web_plus"
  h3_common_plus:
    path: "../h3_common_plus"
  geojson2h3_plus:
    path: "../geojson2h3_plus"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.h3_flutter
        pluginClass: H3FlutterPlugin
      ios:
        pluginClass: H3FlutterPlugin
      macos:
        pluginClass: H3FlutterPlugin
      web:
        default_package: h3_web_plus
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
